language: d

install:
  - sudo apt-get install -y imagemagick libmagickwand4 libmagickwand-dev
  - git clone https://github.com/rossdylan/libfab
  - make -C libfab
  - sudo make -C libfab install
  - export LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"

d:
  - dmd
  - gdc
  - ldc
  - dmd-2.067.1
  - gdc-4.9.0
  - ldc-0.14.0
